export const cityNameMap = {

    // KOREA
    "Seoul": "서울",
    "Gyeonggi-do": "경기도",
    "Busan": "부산",
    "Incheon": "인천",
    "Daegu": "대구",
    "Daejeon": "대전",
    "Gwangju": "광주",
    "Suwon": "수원",
    "Ulsan": "울산",
    "Changwon": "창원",
    "Seongnam": "성남",
    "Goyang": "고양",
    "Yongin": "용인",
    "Bucheon": "부천",
    "Ansan": "안산",
    "Cheongju": "청주",
    "Jeonju": "전주",
    "Cheonan": "천안",
    "Namyangju": "남양주",
    "Hwaseong": "화성",
    "Pohang": "포항",
    "Gimhae": "김해",
    "Jeju City": "제주",
    "Gimpo": "김포",
    "Pyeongtaek": "평택",
    "Siheung": "시흥",
    "Uijeongbu": "의정부",
    "Gangneung": "강릉",
    "Iksan": "익산",
    "Gumi": "구미",
    "Suncheon": "순천",
    "Gunsan": "군산",
    "Wonju": "원주",
    "Mokpo": "목포",
    "Chuncheon": "춘천",
    "Andong": "안동",
    "Asan": "아산",
    "Gwangmyeong": "광명",
    "Tongyeong": "통영",
    "Yangsan": "양산",
    "Geoje": "거제",
    "Sejong": "세종",
    "Osan": "오산",
    "Gunpo": "군포",
    "Gwangju-si": "광주시",
    "Yangju": "양주",
    "Ganghwa": "강화",
    "Yeosu": "여수",
    "Damyang": "담양",
    "Jinju": "진주",
    "Okcheon": "옥천",
    "Yeongju": "영주",
    "Donghae": "동해",
    "Taebaek": "태백",
    "Samcheok": "삼척",
    "Jecheon": "제천",
    "Boryeong": "보령",
    "Nonsan": "논산",
    "Boeun": "보은",
    "Muju": "무주",
    "Yeongcheon": "영천",
    "Gyeongju": "경주",
    "Miryang": "밀양",
    "Sacheon": "사천",
    "Namwon": "남원",
    "Cheongju-si": "청주",
    "Jeju-do": "제주",
    "Ulchin": "울진",

    // USA
    "New York": "뉴욕",
    "Los Angeles": "로스앤젤레스",
    "Chicago": "시카고",
    "Houston": "휴스턴",
    "Phoenix": "피닉스",
    "Philadelphia": "필라델피아",
    "San Antonio": "샌안토니오",
    "San Diego": "샌디에이고",
    "Dallas": "댈러스",
    "San Jose": "산호세",

    // UK
    "London": "런던",
    "Manchester": "맨체스터",
    "Birmingham": "버밍엄",
    "Glasgow": "글래스고",
    "Liverpool": "리버풀",

    // Japan
    "Tokyo": "도쿄",
    "Osaka": "오사카",
    "Kyoto": "교토",
    "Yokohama": "요코하마",
    "Sapporo": "삿포로",

    // China
    "Beijing": "베이징",
    "Shanghai": "상하이",
    "Guangzhou": "광저우",
    "Shenzhen": "선전",
    "Chengdu": "청두",

    // France
    "Paris": "파리",
    "Lyon": "리옹",
    "Marseille": "마르세유",
    "Toulouse": "툴루즈",

    // Germany
    "Berlin": "베를린",
    "Munich": "뮌헨",
    "Frankfurt": "프랑크푸르트",
    "Hamburg": "함부르크",

    // Canada
    "Toronto": "토론토",
    "Vancouver": "밴쿠버",
    "Montreal": "몬트리올",
    "Calgary": "캘거리",

    // Australia
    "Sydney": "시드니",
    "Melbourne": "멜버른",
    "Brisbane": "브리즈번",
    "Perth": "퍼스",

    // Others
    "Moscow": "모스크바",
    "Madrid": "마드리드",
    "Rome": "로마",
    "Istanbul": "이스탄불",
    "Bangkok": "방콕",
    "Dubai": "두바이",
    "Singapore": "싱가포르",
    "New Delhi": "뉴델리",
    "Mexico City": "멕시코시티",
    "Cairo": "카이로"
  };

  export default cityNameMap;